name: Worker CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint (basic)
      run: |
        pip install flake8
        flake8 app

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: |
        docker build -t ferrum-worker:${{ github.sha }} .

    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag image
      run: |
            docker tag ferrum-worker:${{ github.sha }} ghcr.io/${{ github.repository }}/worker:${{ github.sha }}

    - name: Push image
      run: |
        docker push ghcr.io/${{ github.repository }}/worker:${{ github.sha }}

    - name: Tag latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ferrum-worker:${{ github.sha }} ghcr.io/${{ github.repository }}/worker:latest
        
    - name: Push latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/${{ github.repository }}/worker:latest
